export type {
  ApiCcaDetail,
  ApiClassDetail,
  ApiCreateCustomGroupResponse,
  ApiCustomGroupDetail,
  ApiCustomGroupDetailStudent,
  ApiCustomGroupSharedStaff,
  ApiCustomGroupSummary,
  ApiCustomGroupsList,
  ApiGroupsAssigned,
  ApiGroupsAssignedCcaGroup,
  ApiGroupsAssignedClass,
  ApiSchoolClass,
  ApiSchoolStaff,
  ApiSchoolStudent,
} from '~/features/posts/api/types';
